# welcome to numpy tutorial

In [100]:
import numpy as np
import pandas as pd

In [2]:
myarr = np.array([[1,2,3,4]],np.int64)

In [3]:
myarr[0,1]

np.int64(2)

In [4]:
myarr.dtype

dtype('int64')

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr[0,1]=45

In [7]:
myarr

array([[ 1, 45,  3,  4]])

# 5 ways to create numpyarrays: conversion from other python structure

* from list

In [8]:
listarray = np.array([[1,2,3],[22,43,12],[45,78,5]])
listarray

array([[ 1,  2,  3],
       [22, 43, 12],
       [45, 78,  5]])

In [9]:
listarray.shape


(3, 3)

In [10]:
listarray.size

9

In [11]:
listarray.dtype

dtype('int64')

In [12]:
np.array({1,23,1})

array({1, 23}, dtype=object)

In [13]:
zeros = np.zeros((2,3))

In [15]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
lspace=np.linspace(1,2,4)
lspace

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [34]:
np.empty((4,6))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.11522054e-307, 1.42413555e-306, 1.78019082e-306],
       [1.37960147e-306, 1.33511562e-306, 2.22518251e-306,
        1.33511969e-306, 1.78022342e-306, 1.05700345e-307],
       [1.69118108e-306, 8.06632139e-308, 1.20160711e-306,
        1.69119330e-306, 2.22518251e-306, 1.33511969e-306],
       [1.60220393e-306, 1.33511562e-306, 7.56602523e-307,
        1.95820760e-306, 9.34601642e-307, 1.42410974e-306]])

In [37]:
np.empty_like(lspace)

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [49]:
arr=np.reshape([1,2,3,4,5,6],(2,3))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
arr.ravel()

array([1, 2, 3, 4, 5, 6])

# axis


In [58]:
x=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
arr.sum(axis=0) #FOR COLOUNMS

array([12, 15, 18])

In [54]:
arr.sum(axis=1) #FOR ROWS

array([ 6, 15, 24])

In [55]:
arr.T #traverse

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [56]:
arr.flat

In [59]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [61]:
arr.ndim

2

In [62]:
import sys

In [96]:
py_arr=[0,1,2,3]

In [97]:
np_arr=np.array(py_arr)

In [98]:
sys.getsizeof(1)

28

In [99]:
np_arr.itemsize

8